name: Regression tests running on Linux ARM64

on:
  push:
    branches:
      - 'fix_regression_arm'

jobs:
  build_on_arm64:
    name: Run the jobs on Linux ARM64
    uses: './.github/workflows/regression.yml'
    with:
      runner: 'ubuntu-24.04-arm'
